export const GET_FINANCE_DASHBOARD = 'GET_FINANCE_DASHBOARD';
export const GET_FINANCE_DASHBOARD_PENDING = 'GET_FINANCE_DASHBOARD_PENDING';
export const GET_FINANCE_DASHBOARD_SUCCESS = 'GET_FINANCE_DASHBOARD_SUCCESS';
export const GET_FINANCE_DASHBOARD_ERROR = 'GET_FINANCE_DASHBOARD_ERROR';

export const GET_FINANCE_TRANSACTIONS = 'GET_FINANCE_TRANSACTIONS';
export const GET_FINANCE_TRANSACTIONS_PENDING = 'GET_FINANCE_TRANSACTIONS_PENDING';
export const GET_FINANCE_TRANSACTIONS_SUCCESS = 'GET_FINANCE_TRANSACTIONS_SUCCESS';
export const GET_FINANCE_TRANSACTIONS_ERROR = 'GET_FINANCE_TRANSACTIONS_ERROR';

export const CREATE_FINANCE_TRANSACTION = 'CREATE_FINANCE_TRANSACTION';
export const CREATE_FINANCE_TRANSACTION_PENDING = 'CREATE_FINANCE_TRANSACTION_PENDING';
export const CREATE_FINANCE_TRANSACTION_SUCCESS = 'CREATE_FINANCE_TRANSACTION_SUCCESS';
export const CREATE_FINANCE_TRANSACTION_ERROR = 'CREATE_FINANCE_TRANSACTION_ERROR';

export const GET_FINANCE_TRANSACTION = 'GET_FINANCE_TRANSACTION';
export const GET_FINANCE_TRANSACTION_PENDING = 'GET_FINANCE_TRANSACTION_PENDING';
export const GET_FINANCE_TRANSACTION_SUCCESS = 'GET_FINANCE_TRANSACTION_SUCCESS';
export const GET_FINANCE_TRANSACTION_ERROR = 'GET_FINANCE_TRANSACTION_ERROR';

export const UPDATE_FINANCE_TRANSACTION = 'UPDATE_FINANCE_TRANSACTION';
export const UPDATE_FINANCE_TRANSACTION_PENDING = 'UPDATE_FINANCE_TRANSACTION_PENDING';
export const UPDATE_FINANCE_TRANSACTION_SUCCESS = 'UPDATE_FINANCE_TRANSACTION_SUCCESS';
export const UPDATE_FINANCE_TRANSACTION_ERROR = 'UPDATE_FINANCE_TRANSACTION_ERROR';

export const DELETE_FINANCE_TRANSACTION = 'DELETE_FINANCE_TRANSACTION';
export const DELETE_FINANCE_TRANSACTION_PENDING = 'DELETE_FINANCE_TRANSACTION_PENDING';
export const DELETE_FINANCE_TRANSACTION_SUCCESS = 'DELETE_FINANCE_TRANSACTION_SUCCESS';
export const DELETE_FINANCE_TRANSACTION_ERROR = 'DELETE_FINANCE_TRANSACTION_ERROR';

export const GET_FINANCE_MONTHLY_REPORT = 'GET_FINANCE_MONTHLY_REPORT';
export const GET_FINANCE_MONTHLY_REPORT_PENDING = 'GET_FINANCE_MONTHLY_REPORT_PENDING';
export const GET_FINANCE_MONTHLY_REPORT_SUCCESS = 'GET_FINANCE_MONTHLY_REPORT_SUCCESS';
export const GET_FINANCE_MONTHLY_REPORT_ERROR = 'GET_FINANCE_MONTHLY_REPORT_ERROR';

export const GET_FINANCE_YEARLY_REPORT = 'GET_FINANCE_YEARLY_REPORT';
export const GET_FINANCE_YEARLY_REPORT_PENDING = 'GET_FINANCE_YEARLY_REPORT_PENDING';
export const GET_FINANCE_YEARLY_REPORT_SUCCESS = 'GET_FINANCE_YEARLY_REPORT_SUCCESS';
export const GET_FINANCE_YEARLY_REPORT_ERROR = 'GET_FINANCE_YEARLY_REPORT_ERROR';
