export const ADD_SUPER_ADMIN = 'ADD_SUPER_ADMIN';
export const ADD_SUPER_ADMIN_SUCCESS = 'ADD_SUPER_ADMIN_SUCCESS';
export const ADD_SUPER_ADMIN_ERROR = 'ADD_SUPER_ADMIN_ERROR';
export const ADD_SUPER_ADMIN_PENDING = 'ADD_SUPER_ADMIN_PENDING';

export const UPDATE_SUPER_ADMIN = 'UPDATE_SUPER_ADMIN';
export const UPDATE_SUPER_ADMIN_SUCCESS = 'UPDATE_SUPER_ADMIN_SUCCESS';
export const UPDATE_SUPER_ADMIN_ERROR = 'UPDATE_SUPER_ADMIN_ERROR';
export const UPDATE_SUPER_ADMIN_PENDING = 'UPDATE_SUPER_ADMIN_PENDING';

export const GET_SUPER_ADMIN_LIST = 'GET_SUPER_ADMIN_LIST';
export const GET_SUPER_ADMIN_LIST_SUCCESS = 'GET_SUPER_ADMIN_LIST_SUCCESS';
export const GET_SUPER_ADMIN_LIST_ERROR = 'GET_SUPER_ADMIN_LIST_ERROR';
export const GET_SUPER_ADMIN_LIST_PENDING = 'GET_SUPER_ADMIN_LIST_PENDING';
