export const ADD_INSTRUCTOR_DATA = 'Add_INSTRUCTOR_DATA';
export const ADD_INSTRUCTOR_DATA_SUCCESS = 'ADD_INSTRUCTOR_DATA_SUCCESS';
export const ADD_INSTRUCTOR_DATA_ERROR = 'ADD_INSTRUCTOR_DATA_ERROR';
export const ADD_INSTRUCTOR_DATA_PENDING = 'ADD_INSTRUCTOR_DATA_PENDING';

export const UPDATE_INSTRUCTOR_DATA = 'UPDATE_INSTRUCTOR_DATA';
export const UPDATE_INSTRUCTOR_DATA_SUCCESS = 'UPDATE_INSTRUCTOR_DATA_SUCCESS';
export const UPDATE_INSTRUCTOR_DATA_ERROR = 'UPDATE_INSTRUCTOR_DATA_ERROR';
export const UPDATE_INSTRUCTOR_DATA_PENDING = 'UPDATE_INSTRUCTOR_DATA_PENDING';

export const GET_INSTRUCTOR_LIST = 'GET_INSTRUCTOR_LIST';
export const GET_INSTRUCTOR_LIST_SUCCESS = 'GET_INSTRUCTOR_SUCCESS';
export const GET_INSTRUCTOR_LIST_ERROR = 'GET_INSTRUCTOR_LIST_ERROR';
export const GET_INSTRUCTOR_LIST_PENDING = 'GET_INSTRUCTOR_LIST_PENDING';

export const DELETE_INSTRUCTOR_DATA = 'DELETE_INSTRUCTOR_DATA';
export const DELETE_INSTRUCTOR_DATA_SUCCESS = 'DELETE_INSTRUCTOR_DATA_SUCCESS';
export const DELETE_INSTRUCTOR_DATA_ERROR = 'DELETE_INSTRUCTOR_DATA_ERROR';
export const DELETE_INSTRUCTOR_DATA_PENDING = 'DELETE_INSTRUCTOR_DATA_PENDING';