export const ADD_ENQUIRIES_DATA = 'ADD_ENQUIRIES_DATA';
export const ADD_ENQUIRIES_DATA_SUCCESS = 'ADD_ENQUIRIES_DATA_SUCCESS';
export const ADD_ENQUIRIES_DATA_ERROR = 'ADD_ENQUIRIES_DATA_ERROR';
export const ADD_ENQUIRIES_DATA_PENDING = 'ADD_ENQUIRIES_DATA_PENDING';

export const UPDATE_ENQUIRIES_DATA = 'UPDATE_ENQUIRIES_DATA';
export const UPDATE_ENQUIRIES_DATA_SUCCESS = 'UPDATE_ENQUIRIES_DATA_SUCCESS';
export const UPDATE_ENQUIRIES_DATA_ERROR = 'UPDATE_ENQUIRIES_DATA_ERROR';
export const UPDATE_ENQUIRIES_DATA_PENDING = 'UPDATE_ENQUIRIES_DATA_PENDING';

export const GET_ENQUIRIES_LIST = 'GET_ENQUIRIES_LIST';
export const GET_ENQUIRIES_LIST_SUCCESS = 'GET_ENQUIRIES_SUCCESS';
export const GET_ENQUIRIES_LIST_ERROR = 'GET_ENQUIRIES_LIST_ERROR';
export const GET_ENQUIRIES_LIST_PENDING = 'GET_ENQUIRIES_LIST_PENDING';

export const DELETE_ENQUIRIES_DATA = 'DELETE_ENQUIRIES_DATA';
export const DELETE_ENQUIRIES_DATA_SUCCESS = 'DELETE_ENQUIRIES_DATA_SUCCESS';
export const DELETE_ENQUIRIES_DATA_ERROR = 'DELETE_ENQUIRIES_DATA_ERROR';
export const DELETE_ENQUIRIES_DATA_PENDING = 'DELETE_ENQUIRIES_DATA_PENDING';