export const ADD_STUDENT_PAYMENT_DATA = 'Add_STUDENT_PAYMENT_DATA';
export const ADD_STUDENT_PAYMENT_DATA_SUCCESS = 'ADD_STUDENT_PAYMENT_DATA_SUCCESS';
export const ADD_STUDENT_PAYMENT_DATA_ERROR = 'ADD_STUDENT_PAYMENT_DATA_ERROR';
export const ADD_STUDENT_PAYMENT_DATA_PENDING = 'ADD_STUDENT_PAYMENT_DATA_PENDING';