export const DELETE_STUDENT_DATA = 'DELETE_STUDENT_DATA';
export const DELETE_STUDENT_DATA_SUCCESS = 'DELETE_STUDENT_DATA_SUCCESS';
export const DELETE_STUDENT_DATA_ERROR = 'DELETE_STUDENT_DATA_ERROR';
export const DELETE_STUDENT_DATA_PENDING = 'DELETE_STUDENT_DATA_PENDING';