export const ADD_EXPENSES_DATA = 'ADD_EXPENSES_DATA';
export const ADD_EXPENSES_DATA_SUCCESS = 'ADD_EXPENSES_DATA_SUCCESS';
export const ADD_EXPENSES_DATA_ERROR = 'ADD_EXPENSES_DATA_ERROR';
export const ADD_EXPENSES_DATA_PENDING = 'ADD_EXPENSES_DATA_PENDING';

export const UPDATE_EXPENSES_DATA = 'UPDATE_EXPENSES_DATA';
export const UPDATE_EXPENSES_DATA_SUCCESS = 'UPDATE_EXPENSES_DATA_SUCCESS';
export const UPDATE_EXPENSES_DATA_ERROR = 'UPDATE_EXPENSES_DATA_ERROR';
export const UPDATE_EXPENSES_DATA_PENDING = 'UPDATE_EXPENSES_DATA_PENDING';

export const DELETE_EXPENSES_DATA = 'DELETE_EXPENSES_DATA';
export const DELETE_EXPENSES_DATA_SUCCESS = 'DELETE_EXPENSES_DATA_SUCCESS';
export const DELETE_EXPENSES_DATA_ERROR = 'DELETE_EXPENSES_DATA_ERROR';
export const DELETE_EXPENSES_DATA_PENDING = 'DELETE_EXPENSES_DATA_PENDING';

export const GET_EXPENSES_LIST = 'GET_EXPENSES_LIST';
export const GET_EXPENSES_LIST_SUCCESS = 'GET_EXPENSES_SUCCESS';
export const GET_EXPENSES_LIST_ERROR = 'GET_EXPENSES_LIST_ERROR';
export const GET_EXPENSES_LIST_PENDING = 'GET_EXPENSES_LIST_PENDING';