version: "3.9"
services:
  drivedesk-prod-ui:
    image: ${UI_IMAGE_TAG}
    container_name: drivedesk-prod-ui
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - drivedesk-shared-network
    environment:
      - API_HOST=${API_HOST}

networks:
  drivedesk-shared-network:
    external: true
