  drivedesk-dev-ui:
    image: {{UI_IMAGE_TAG}}
    container_name: drivedesk-dev-ui
    restart: unless-stopped
    ports:
      - "3000:80"
      
  networks:
  default:
    external:
      name: drivedesk-shared-network
