version: "3.9"

services:
  drivedesk-dev-ui:
    image: ${UI_IMAGE_TAG}
    container_name: drivedesk-dev-ui
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - drivedesk-shared-network

networks:
  drivedesk-shared-network:
    external: true
