export const GET_TENANT_USAGE_DASHBOARD = 'GET_TENANT_USAGE_DASHBOARD';
export const GET_TENANT_USAGE_DASHBOARD_PENDING = 'GET_TENANT_USAGE_DASHBOARD_PENDING';
export const GET_TENANT_USAGE_DASHBOARD_SUCCESS = 'GET_TENANT_USAGE_DASHBOARD_SUCCESS';
export const GET_TENANT_USAGE_DASHBOARD_ERROR = 'GET_TENANT_USAGE_DASHBOARD_ERROR';

export const GET_TENANT_USAGE_LIST = 'GET_TENANT_USAGE_LIST';
export const GET_TENANT_USAGE_LIST_PENDING = 'GET_TENANT_USAGE_LIST_PENDING';
export const GET_TENANT_USAGE_LIST_SUCCESS = 'GET_TENANT_USAGE_LIST_SUCCESS';
export const GET_TENANT_USAGE_LIST_ERROR = 'GET_TENANT_USAGE_LIST_ERROR';
