export const GET_STUDENTS_LIST = 'GET_STUDENTS_LIST';
export const GET_STUDENTS_LIST_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_LIST_ERROR = 'GET_STUDENTS_LIST_ERROR';
export const GET_STUDENTS_LIST_PENDING = 'GET_STUDENTS_LIST_PENDING';

export const GET_STUDENTS_FILTER_LIST = 'GET_STUDENTS_FILTER_LIST';
export const GET_STUDENTS_FILTER_LIST_SUCCESS = 'GET_STUDENTS_FILTER_LIST_SUCCESS';
export const GET_STUDENTS_FILTER_LIST_ERROR = 'GET_STUDENTS_FILTER_LIST_ERROR';
export const GET_STUDENTS_FILTER_LIST_PENDING = 'GET_STUDENTS_FILTER_LIST_PENDING';

export const GET_STUDENTS_RECEIPT = 'GET_STUDENTS_RECEIPT';
export const GET_STUDENTS_RECEIPT_SUCCESS = 'GET_STUDENTS_RECEIPT_SUCCESS';
export const GET_STUDENTS_RECEIPT_ERROR = 'GET_STUDENTS_RECEIPT_ERROR';
export const GET_STUDENTS_RECEIPT_PENDING = 'GET_STUDENTS_RECEIPT_PENDING';