export const GET_STUDENTS_LIST = 'GET_STUDENTS_LIST';
export const GET_STUDENTS_LIST_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENTS_LIST_ERROR = 'GET_STUDENTS_LIST_ERROR';
export const GET_STUDENTS_LIST_PENDING = 'GET_STUDENTS_LIST_PENDING';