export const LOGIN_USER_DATA_SUCCESS = 'LOGIN_USER_DATA_SUCCESS';
export const LOGIN_USER_DATA_ERROR = 'LOGIN_USER_DATA_ERROR';
export const LOGIN_USER_DATA_PENDING = 'LOGIN_USER_DATA_PENDING';
export const LOGIN_USER_DATA = 'LOGIN_USER_DATA';