export const LOGIN_USER_DATA_SUCCESS = 'LOGIN_USER_DATA_SUCCESS';
export const LOGIN_USER_DATA_ERROR = 'LOGIN_USER_DATA_ERROR';
export const LOGIN_USER_DATA_PENDING = 'LOGIN_USER_DATA_PENDING';
export const LOGIN_USER_DATA = 'LOGIN_USER_DATA';

export const REQUEST_LOGIN_OTP = 'REQUEST_LOGIN_OTP';
export const REQUEST_LOGIN_OTP_PENDING = 'REQUEST_LOGIN_OTP_PENDING';
export const REQUEST_LOGIN_OTP_SUCCESS = 'REQUEST_LOGIN_OTP_SUCCESS';
export const REQUEST_LOGIN_OTP_ERROR = 'REQUEST_LOGIN_OTP_ERROR';

export const VERIFY_LOGIN_OTP = 'VERIFY_LOGIN_OTP';
export const VERIFY_LOGIN_OTP_PENDING = 'VERIFY_LOGIN_OTP_PENDING';
export const VERIFY_LOGIN_OTP_SUCCESS = 'VERIFY_LOGIN_OTP_SUCCESS';
export const VERIFY_LOGIN_OTP_ERROR = 'VERIFY_LOGIN_OTP_ERROR';

export const GET_TENANT_LOGO = 'GET_TENANT_LOGO';
export const GET_TENANT_LOGO_PENDING = 'GET_TENANT_LOGO_PENDING';
export const GET_TENANT_LOGO_SUCCESS = 'GET_TENANT_LOGO_SUCCESS';
export const GET_TENANT_LOGO_ERROR = 'GET_TENANT_LOGO_ERROR';
