export const GET_TRAINING_SESSION_LIST = 'GET_TRAINING_SESSION_LIST';
export const GET_TRAINING_SESSION_LIST_SUCCESS = 'GET_TRAINING_SESSION_LIST_SUCCESS';
export const GET_TRAINING_SESSION_LIST_ERROR = 'GET_TRAINING_SESSION_LIST_ERROR';
export const GET_TRAINING_SESSION_LIST_PENDING = 'GET_TRAINING_SESSION_LIST_PENDING';

export const GET_TRAINING_SESSION_FILTER_LIST = 'GET_TRAINING_SESSION_FILTER_LIST';
export const GET_TRAINING_SESSION_FILTER_LIST_SUCCESS = 'GET_TRAINING_SESSION_FILTER_LIST_SUCCESS';
export const GET_TRAINING_SESSION_FILTER_LIST_ERROR = 'GET_TRAINING_SESSION_FILTER_LIST_ERROR';
export const GET_TRAINING_SESSION_FILTER_LIST_PENDING = 'GET_TRAINING_SESSION_FILTER_LIST_PENDING';

export const UPDATE_TRAINING_SESSION_DATA = 'UPDATE_TRAINING_SESSION_DATA';
export const UPDATE_TRAINING_SESSION_DATA_SUCCESS = 'UPDATE_TRAINING_SESSION_DATA_SUCCESS';
export const UPDATE_TRAINING_SESSION_DATA_ERROR = 'UPDATE_TRAINING_SESSION_DATA_ERROR';
export const UPDATE_TRAINING_SESSION_DATA_PENDING = 'UPDATE_TRAINING_SESSION_DATA_PENDING';