export const ENDPOINTS = {
    userLogin: 'auth/login',
    getAllStudents: 'getAllStudents',
    addStudent: 'students/',
    deleteStudent: 'students/application-number/',
    editStudent: 'students/application-number/',
    addTariff: 'tariff_router/tariff',
    editTariff: 'tariff_router/tariff/',
    getAllTariffs: 'tariff_router/tariff',
    deleteTariff: 'tariff_router/tariff/',
    addInstructor: 'instructors/',
    editInstructor: 'instructors/',
    getAllInstructors: 'instructors/fetchAllInstructors',
    deleteInstructor: 'instructors/',
    addEnquiries: 'enquiries/save-enquiry',
    editEnquiries: 'enquiries/',
    getAllEnquiries: 'enquiries/fetchAll',
    deleteEnquiries: 'enquiries/',
    getAllStudentsFilter: 'admin/students/filter',
    getDashboardSummary: 'dashboard/summary',
    getStudentReceipt: 'student/receipt-preview-by-receiptno/',
    addStudentPayment: 'students/',
} 