export const ADD_TARIFF_DATA = 'Add_TARIFF_DATA';
export const ADD_TARIFF_DATA_SUCCESS = 'ADD_TARIFF_DATA_SUCCESS';
export const ADD_TARIFF_DATA_ERROR = 'ADD_TARIFF_DATA_ERROR';
export const ADD_TARIFF_DATA_PENDING = 'ADD_TARIFF_DATA_PENDING';

export const UPDATE_TARIFF_DATA = 'UPDATE_TARIFF_DATA';
export const UPDATE_TARIFF_DATA_SUCCESS = 'UPDATE_TARIFF_DATA_SUCCESS';
export const UPDATE_TARIFF_DATA_ERROR = 'UPDATE_TARIFF_DATA_ERROR';
export const UPDATE_TARIFF_DATA_PENDING = 'UPDATE_TARIFF_DATA_PENDING';

export const GET_TARIFF_LIST = 'GET_TARIFF_LIST';
export const GET_TARIFF_LIST_SUCCESS = 'GET_TARIFF_SUCCESS';
export const GET_TARIFF_LIST_ERROR = 'GET_TARIFF_LIST_ERROR';
export const GET_TARIFF_LIST_PENDING = 'GET_TARIFF_LIST_PENDING';

export const DELETE_TARIFF_DATA = 'DELETE_TARIFF_DATA';
export const DELETE_TARIFF_DATA_SUCCESS = 'DELETE_TARIFF_DATA_SUCCESS';
export const DELETE_TARIFF_DATA_ERROR = 'DELETE_TARIFF_DATA_ERROR';
export const DELETE_TARIFF_DATA_PENDING = 'DELETE_TARIFF_DATA_PENDING';