export const GET_MY_SUBSCRIPTION = "GET_MY_SUBSCRIPTION";
export const GET_MY_SUBSCRIPTION_PENDING = "GET_MY_SUBSCRIPTION_PENDING";
export const GET_MY_SUBSCRIPTION_SUCCESS = "GET_MY_SUBSCRIPTION_SUCCESS";
export const GET_MY_SUBSCRIPTION_ERROR = "GET_MY_SUBSCRIPTION_ERROR";

export const GET_SUBSCRIPTION_SETTINGS = "GET_SUBSCRIPTION_SETTINGS";
export const GET_SUBSCRIPTION_SETTINGS_PENDING = "GET_SUBSCRIPTION_SETTINGS_PENDING";
export const GET_SUBSCRIPTION_SETTINGS_SUCCESS = "GET_SUBSCRIPTION_SETTINGS_SUCCESS";
export const GET_SUBSCRIPTION_SETTINGS_ERROR = "GET_SUBSCRIPTION_SETTINGS_ERROR";

export const UPDATE_SUBSCRIPTION_SETTINGS = "UPDATE_SUBSCRIPTION_SETTINGS";
export const UPDATE_SUBSCRIPTION_SETTINGS_PENDING = "UPDATE_SUBSCRIPTION_SETTINGS_PENDING";
export const UPDATE_SUBSCRIPTION_SETTINGS_SUCCESS = "UPDATE_SUBSCRIPTION_SETTINGS_SUCCESS";
export const UPDATE_SUBSCRIPTION_SETTINGS_ERROR = "UPDATE_SUBSCRIPTION_SETTINGS_ERROR";

export const INITIALIZE_SUBSCRIPTION = "INITIALIZE_SUBSCRIPTION";
export const INITIALIZE_SUBSCRIPTION_PENDING = "INITIALIZE_SUBSCRIPTION_PENDING";
export const INITIALIZE_SUBSCRIPTION_SUCCESS = "INITIALIZE_SUBSCRIPTION_SUCCESS";
export const INITIALIZE_SUBSCRIPTION_ERROR = "INITIALIZE_SUBSCRIPTION_ERROR";

export const RENEW_SUBSCRIPTION = "RENEW_SUBSCRIPTION";
export const RENEW_SUBSCRIPTION_PENDING = "RENEW_SUBSCRIPTION_PENDING";
export const RENEW_SUBSCRIPTION_SUCCESS = "RENEW_SUBSCRIPTION_SUCCESS";
export const RENEW_SUBSCRIPTION_ERROR = "RENEW_SUBSCRIPTION_ERROR";

export const PROCESS_SUBSCRIPTIONS = "PROCESS_SUBSCRIPTIONS";
export const PROCESS_SUBSCRIPTIONS_PENDING = "PROCESS_SUBSCRIPTIONS_PENDING";
export const PROCESS_SUBSCRIPTIONS_SUCCESS = "PROCESS_SUBSCRIPTIONS_SUCCESS";
export const PROCESS_SUBSCRIPTIONS_ERROR = "PROCESS_SUBSCRIPTIONS_ERROR";
export const RESET_SUBSCRIPTION_STATE = "RESET_SUBSCRIPTION_STATE";
