export const ADD_STUDENT_DATA = 'Add_STUDENT_DATA';
export const ADD_STUDENT_DATA_SUCCESS = 'ADD_STUDENT_DATA_SUCCESS';
export const ADD_STUDENT_DATA_ERROR = 'ADD_STUDENT_DATA_ERROR';
export const ADD_STUDENT_DATA_PENDING = 'ADD_STUDENT_DATA_PENDING';

export const UPDATE_STUDENT_DATA = 'UPDATE_STUDENT_DATA';
export const UPDATE_STUDENT_DATA_SUCCESS = 'UPDATE_STUDENT_DATA_SUCCESS';
export const UPDATE_STUDENT_DATA_ERROR = 'UPDATE_STUDENT_DATA_ERROR';
export const UPDATE_STUDENT_DATA_PENDING = 'UPDATE_STUDENT_DATA_PENDING';