export const GET_DASHBOARD_SUMMARY = 'GET_DASHBOARD_SUMMARY';
export const GET_DASHBOARD_SUMMARY_SUCCESS = 'GET_DASHBOARD_SUMMARY_SUCCESS';
export const GET_DASHBOARD_SUMMARY_ERROR = 'GET_DASHBOARD_SUMMARY_ERROR';
export const GET_DASHBOARD_SUMMARY_PENDING = 'GET_DASHBOARD_SUMMARY_PENDING';

export const GET_OUTSTANDING_FEES = 'GET_OUTSTANDING_FEES';
export const GET_OUTSTANDING_FEES_SUCCESS = 'GET_OUTSTANDING_FEES_SUCCESS';
export const GET_OUTSTANDING_FEES_ERROR = 'GET_OUTSTANDING_FEES_ERROR';
export const GET_OUTSTANDING_FEES_PENDING = 'GET_OUTSTANDING_FEES_PENDING';