export const GET_DASHBOARD_SUMMARY = 'GET_DASHBOARD_SUMMARY';
export const GET_DASHBOARD_SUMMARY_SUCCESS = 'GET_DASHBOARD_SUMMARY_SUCCESS';
export const GET_DASHBOARD_SUMMARY_ERROR = 'GET_DASHBOARD_SUMMARY_ERROR';
export const GET_DASHBOARD_SUMMARY_PENDING = 'GET_DASHBOARD_SUMMARY_PENDING';

export const GET_OUTSTANDING_FEES = 'GET_OUTSTANDING_FEES';
export const GET_OUTSTANDING_FEES_SUCCESS = 'GET_OUTSTANDING_FEES_SUCCESS';
export const GET_OUTSTANDING_FEES_ERROR = 'GET_OUTSTANDING_FEES_ERROR';
export const GET_OUTSTANDING_FEES_PENDING = 'GET_OUTSTANDING_FEES_PENDING';

export const HISTORICAL_PAYMENT_ADJUSTMENT = 'HISTORICAL_PAYMENT_ADJUSTMENT';
export const HISTORICAL_PAYMENT_ADJUSTMENT_SUCCESS = 'HISTORICAL_PAYMENT_ADJUSTMENT_SUCCESS';
export const HISTORICAL_PAYMENT_ADJUSTMENT_ERROR = 'HISTORICAL_PAYMENT_ADJUSTMENT_ERROR';
export const HISTORICAL_PAYMENT_ADJUSTMENT_PENDING = 'HISTORICAL_PAYMENT_ADJUSTMENT_PENDING';