name: deploy-ui-dev

on:
  push:
    branches:
      - develop
    paths:
      - "drivedesk-crm-ui/**"
      - ".github/workflows/deploy-dev-ui.yml"

jobs:
  deploy-ui:
    name: SSH and Deploy to Dev VM
    runs-on: ubuntu-latest

    env:
      UI_IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_KEY }}

      - name: SSH and Deploy to Dev VM
        run: |
          TAG=${{ github.sha }}
          ssh -o StrictHostKeyChecking=no vinoothiniddi@${{ secrets.GCP_VM_IP }} \
          "cd ~/drivedesk-crm-ui && \
          echo '💡 Rendering docker-compose-dev.yml with tag $TAG' && \
          UI_IMAGE_TAG=$TAG envsubst < docker-compose-dev.template.yml > docker-compose-dev.yml && \
          docker-compose -f docker-compose-dev.yml pull && \
          docker-compose -f docker-compose-dev.yml down && \
          docker-compose -f docker-compose-dev.yml up -d"

