name: deploy-ui-dev

on:
  push:
    branches:
      - develop
    paths:
      - "drivedesk-crm-ui/**"
      - ".github/workflows/deploy-dev-ui.yml"

jobs:
  deploy-ui:
    name: SSH and Deploy to Dev VM
    runs-on: ubuntu-latest

    env:
      UI_IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_KEY }}

      - name: SSH and Deploy to Dev VM
        run: |
         TAG=${{ github.sha }}
         ssh -o StrictHostKeyChecking=no vinoothiniddi@${{ secrets.GCP_VM_IP }} << EOF
          set -e
          cd ~/drivedesk-crm-ui

          echo "💡 Generating docker-compose-dev.yml with tag ${TAG}"
          echo "image: \\\"asia-south1-docker.pkg.dev/sage-buttress-455713-h4/drivedesk-crm-ui/crm-ui:${TAG}\\\"" > /tmp/.image_line
          sed "/image:/r /tmp/.image_line" docker-compose-dev.template.yml | sed "/image:/d" > docker-compose-dev.yml

          echo "📦 Pulling image"
          docker-compose -f docker-compose-dev.yml pull

          echo "🧹 Stopping old container"
          docker-compose -f docker-compose-dev.yml down

          echo "🚀 Starting new container"
          docker-compose -f docker-compose-dev.yml up -d
         EOF
