name: Deploy React UI to Prod

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag of the image to deploy (e.g., github_sha)'
        required: true
        default: 'latest'

jobs:
  deploy-ui-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_PROD }}

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Set UI Image Tag
        run: echo "UI_IMAGE_TAG=asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID_PROD }}/drivedesk-crm-ui/drivedesk-dev-ui:${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV

      - name: Generate docker-compose-prod.yml from template
        run: |
          cp docker-compose-prod.template.yml docker-compose-prod.yml
          sed -i "s|{{UI_IMAGE_TAG}}|$UI_IMAGE_TAG|g" docker-compose-prod.yml

      - name: SSH and Deploy to Prod VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_VM_IP_PROD }}
          username: ${{ secrets.GCP_VM_USER_PROD }}
          key: ${{ secrets.GCP_SSH_KEY_PROD }}
          script: |
            cd ~/drivedesk-crm-ui
            docker-compose -f docker-compose-prod.template.yml pull
            docker-compose -f docker-compose-prod.template.yml down
            docker-compose -f docker-compose-prod.template.yml up -d
